# Site settings
title: Blog de Charles Martin
email: martinaware@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Meilleur blog technique du monde
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmartingatignol.github.io" # the base hostname & protocol for your site
twitter_username: cmartingatignol
github_username:  cmartingatignol

# Build settings
markdown: kramdown
